#!/usr/bin/env bash
# Usage: ./1-
# Configure your domain zone

domain_subdomain() {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk ' {print "The subdomain " $! " is a  " $2 " record and points to " $3}"
}

if [ "$#" == 1 ]
then
  domain_subdomain "$1" "www"
  domain_subdomain "$1" "lb-01"
  domain_subdomain "$1" "web-01"
  domain_subdomain "$1" "web-02"
elif [ "$#" == 2 ]
then
  domain_subdomain "$1" "$2"
fi
