#!/usr/bin/env bash
# installing a web server nginx

sudo apt-get -y update
sudo apt-get -y install ngnix

touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html

service ngnix start
