#!/usr/bin/env bash
# what i did in task 0. i should make it short and sweet

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
