#!/usr/bin/env bash
# A bash script that displays "To infinity and beyond" indefinately
# in between each iteration of the loop, add a sleep 2

while true
do
	echo "To inifinity and beyond"
	sleep 2
done
