#!/usr/bin/env bash
# A bash script that displays the content of the file /etc/passwd

filename="/etc/passwd"
while IFS= read  -r username userid homedir
do
	echo "$username $userid $homedir" | cut -d: -f 1,3,6
done < $filename
