#!/usr/bin/env bash
# A bash script that displays the bash script for 12 hours and 59 minutes
Hour=0
while [ "$Hour" -le 12 ]
do
	echo "Hour: $Hour"
	min=1
	while [ "$min" -le 59 ]
	do
		echo "$min"
		((min++))
	done
	((Hour++))
done 
